project:
  type: book

book:
  title: "Building Data Packages"
  subtitle: "A guide to engineering and developing research data as a FAIR and tidy data package"
  repo-branch: main
  repo-actions: [issue, edit, source]
  downloads: [pdf]
  site-url: "https://data-pkg-guide.seedcase-project.org"
  repo-url: "https://github.com/seedcase-project/data-pkg-guide"
  date: last-modified
  author:
    - name: "Luke W. Johnston"
      affiliation: "Steno Diabetes Center Aarhus"
      orcid: "https://orcid.org/0000-0003-4169-2616"
  favicon: "_extensions/seedcase-project/seedcase-theme/logos/seedcase/icon.svg"
  search:
    type: textbox
  chapters:
    - index.qmd
    - part: "Overview"
      chapters:
        - docs/index.qmd
        - docs/layout.qmd
        - docs/workflow.qmd
    - part: "Structure"
      chapters:
        - docs/src.qmd
        - docs/raw.qmd
        - docs/staging.qmd
        - docs/resources.qmd
        - docs/metadata.qmd
    - part: "Lifecycle"
      chapters:
        - docs/ci.qmd
        - docs/build.qmd
        - docs/release.qmd
    - part: "Development"
      chapters:
        - docs/tools.qmd
        - docs/setup.qmd
        - docs/config.qmd
        - docs/testing.qmd
        - docs/devex.qmd
    - part: "Management"
      chapters:
        - docs/license.qmd
        - docs/requests.qmd
        - docs/subsets.qmd
  appendices:
    - CHANGELOG.md
    - CONTRIBUTING.md
    - CODE_OF_CONDUCT.md
  tools:
    - icon: github
      href: "https://github.com/seedcase-project/data-pkg-guide"
      aria-label: "GitHub icon: Source repository"
    - icon: house
      href: "https://seedcase-project.org"
      aria-label: "House icon: Main website for the Seedcase Project"
  page-footer:
    center:
      - text: "Licensed under CC BY 4.0"
        href: "LICENSE.md"

format:
  seedcase-theme-html:
    include-before-body:
      - "includes/site-counter.html"
  typst:
    brand: "_extensions/seedcase-project/seedcase-theme/_brand.yml"
    papersize: a4
    margin:
      x: 2cm
      y: 2cm
