# Welcome! {.unnumbered}

::: {.content-visible when-format="html"}
{{< include /includes/_badges.qmd >}}
:::

::: callout-caution
These documents are very much a work in progress and very much incomplete. We
work on it slowly and when we can.
:::

There are little to no resources available online on how to develop data as a
package similar to developing software as a package, e.g. [R
packages](https://r-pkgs.org/), [Python
packages](https://packaging.python.org/), or [Rust
packages](https://doc.rust-lang.org/cargo/). There are many resources on how to
build data warehouses or data lakes/lakehouses, along with many enterprise-level
tools and platforms to build them. However, these are often overengineered and
excessively complicated for the needs within science and research. This guide is
an attempt at providing a practical how-to guide on treating data with a
"product" mindset. We walk through how to build up data following practices from
the software package development cycle so that the final "data product" (or
"data package") is findable, accessible, interoperable, and reusable
([FAIR](https://www.go-fair.org/fair-principles/)) and
[tidy](https://doi.org/10.18637/jss.v059.i10).

::: {.callout-note appearance="default"}
This guide mostly follows the [diátaxis](https://diataxis.fr/how-to-guides/)
"how-to guide" style, though not strictly. It is a living and constantly
evolving guide that is regularly updated as we learn and refine how we work and
develop data packages. We intend to continually update and releasing it with
every update to Zenodo and as GitHub releases. We don't expect this guide to
ever be considered "done".
:::

## Who you are as the reader

We've written these documents considering a few people in mind who we think will
read the documents:

- **New contributors/team members**: This is our primary audience for this
  guide. If you are new to working with us on the Seedcase Project, these
  documents are designed with you in mind.
- **Research software/data engineers**: If you work in another organization or
  group, we write these documents to share our practices with you. You can use
  this either as a guide or as a reference to help you build your own data
  packages and learn how we work.

## Contributing

Check out our [contributing document](CONTRIBUTING.md) for information on how to
contribute to the project.

::: content-hidden
<!-- TODO: Unhide after having more contributors -->
### Contributors

{{< include /includes/_contributors.qmd >}}
:::

## Changes

Check out our [changelog](CHANGELOG.md) for information on what has changed in
each version of the guide. Previous versions can be found in the
[releases](https://github.com/seedcase-project/data-pkg-guide/releases) page of
the GitHub repository.

::: content-hidden
<!-- TODO: Uncomment after building the PDF and uploading as an artifact -->
<!-- TODO: Add Zenodo link here once created -->
The PDF version of the guide is also available in the releases page, as well as
the Zenodo archive.
:::

## How the website is made

The website and PDF (download link on the top of the website's sidebar) are
created using [Quarto](https://quarto.org) to write the material and create the
book format. [GitHub](https://github.com/) hosts the [Git](https://git-scm.com/)
repository of the material, while [GitHub
Actions](https://github.com/features/actions) builds and releases the book with
every change. [Netlify](https://www.netlify.com/) hosts the website and manages
the domain. The source material is on the
[`{{< meta gh.repo >}}`]({{< meta links.github >}}) GitHub repository.
